# Generated by Django 5.0 on 2025-12-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_projectanalysis_executive_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectanalysis",
            name="critical_risks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="immediate_actions",
            field=models.TextField(blank=True),
        ),
    ]
