# Generated by Django 5.0 on 2025-12-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_projectanalysis_critical_risks_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectanalysis",
            old_name="immediate_actions",
            new_name="top_risks",
        ),
    ]
