# Generated by Django 5.0 on 2025-12-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_immediate_actions_projectanalysis_top_risks"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectanalysis",
            name="immediate_actions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
