# Generated by Django 5.0 on 2025-12-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_projectanalysis_immediate_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectanalysis",
            name="impact",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="likelihood",
            field=models.IntegerField(default=0),
        ),
    ]
