# Generated by Django 5.0 on 2026-01-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_projectanalysis_impact_projectanalysis_likelihood"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="structured_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="project",
            name="system_design_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
