# Generated by Django 5.0 on 2026-01-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20260112_1200"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectanalysis",
            name="raw_ai_response",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
