# Generated by Django 5.0 on 2026-01-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_projectanalysis_raw_ai_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectanalysis",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
