# Generated by Django 5.0 on 2026-01-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectanalysis",
            name="dfd_diagram",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="erd_diagram",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="threat_diagram",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectanalysis",
            name="uml_diagram",
            field=models.TextField(blank=True, null=True),
        ),
    ]
